version: "3"
services:
  server:
    container_name: project_server
    build:
      context: ./server
    ports:
      - "8080:8080"
  app:
    container_name: client_app
    build:
      context: ./client
    ports:
      - "3000:3000"
