version: "3"
services:
  server:
    container_name: project_server
    env_file:
      - ./server/.env
    build:
      context: ./server
    ports:
      - "8080:8080"
    volumes:
      - "./src:/home/node/app"
    links:
      - mongo
    networks:
      - mongodb
    depends_on:
      - mongo

  mongo:
    container_name: project_mongo
    image: "mongo:latest"
    ports:
      - "27017:27017"
    volumes:
      - ./database:/data/db
    networks:
      - mongodb
  app:
    container_name: client_app
    build:
      context: ./client
    ports:
      - "3000:3000"

networks:
  mongodb:
    driver: bridge
