version: "3"
services:
  server:
    container_name: project_server
    env_file:
      - ./server/.env
    environment:
      - NODE_ENV=production
    build:
      context: ./server
      target: production
    ports:
      - "3001:3001"
    links:
      - mongo
    networks:
      - mongodb
    depends_on:
      - mongo
    tty: true

  mongo:
    container_name: project_mongo
    restart: always
    image: "mongo:latest"
    ports:
      - "27017:27017"
    volumes:
      - ./database:/data/db
    networks:
      - mongodb

  app:
    container_name: client_app
    environment:
      - NODE_ENV=production
    build:
      target: production
      context: ./client
    ports:
      - "3000:3000"
    tty: true

networks:
  mongodb:
    driver: bridge
