version: "3" # version of docker-compose
services: # list of services
  server: # name of service
    container_name: project_server # name of container
    env_file: # file with environment variables
      - ./server/.env
    environment: # environment variables
      - NODE_ENV=development
    build: # build configuration
      context: ./server
      target: dev
    ports: # ports mapping
      - "3001:3001"
    volumes: # volumes mapping
      - "./server:/usr/src/server"
    links: # links to other services
      - mongo
    networks: # networks
      - mongodb
      - client
    depends_on: # dependencies
      - mongo
    tty: true # allocate pseudo-TTY

  mongo: # name of service
    container_name: project_mongo # name of container
    restart: always # restart policy
    image: "mongo:latest" # image
    ports: # ports mapping
      - "27017:27017"
    volumes: # volumes mapping
      - ./database:/data/db
    networks: # networks
      - mongodb

  app: # name of service
    container_name: client_app # name of container
    environment: # environment variables
      - NODE_ENV=development
    build: # build configuration
      target: dev
      context: ./client
    ports: # ports mapping
      - "3000:3000"
    volumes: # volumes mapping
      - "./client:/usr/src/client"
    tty: true # allocate pseudo-TTY
    networks: # networks
      - client

  elasticsearch: # name of service
    container_name: elasticsearch # name of container
    image: docker.elastic.co/elasticsearch/elasticsearch:8.9.0 # image
    networks: # networks
      - elk
    ports: # ports mapping
      - "9200:9200"
    volumes: # volumes mapping
      - ./elk/elasticsearch/data:/usr/share/elasticsearch/data
    environment: # environment variables
      - "discovery.type=single-node"

  kibana: # name of service
    container_name: kibana # name of container
    image: docker.elastic.co/kibana/kibana:8.9.0 # image
    environment: # environment variables
      ELASTIC_PASSWORD: ${ELASTIC_PASSWORD}
      KIBANA_SYSTEM_PASSWORD: ${KIBANA_SYSTEM_PASSWORD}
    networks: # networks
      - elk
    ports: # ports mapping
      - "5601:5601"
    volumes: # volumes mapping
      - ./elk/kibana/data:/usr/share/kibana/data
      - ./elk/kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml

  logstash: # name of service
    container_name: logstash # name of container
    image: docker.elastic.co/logstash/logstash:8.9.0 # image
    environment: # environment variables
      ELASTIC_PASSWORD: ${ELASTIC_PASSWORD}
    networks: # networks
      - elk
    ports: # ports mapping
      - "5044:5044"
    volumes: # volumes mapping
      - ./elk/logstash/pipeline/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
      - ./elk/logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
    depends_on: # dependencies
      - elasticsearch

  filebeat: # name of service
    container_name: filebeat # name of container
    image: docker.elastic.co/beats/filebeat:8.9.0 # image
    user: root # user
    environment: # environment variables
      ELASTIC_PASSWORD: ${ELASTIC_PASSWORD}
    volumes: # volumes mapping
      - ./elk/filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml
      - /var/lib/docker:/var/lib/docker:ro
      - /var/run/docker.sock:/var/run/docker.sock
    networks: # networks
      - elk
    depends_on: # dependencies
      - elasticsearch
      - logstash

networks: # networks
  mongodb:
    driver: bridge
  elk:
    driver: bridge
  client:
    driver: bridge
